name: Dickerator
options:
  bundleIdPrefix: com.dickerator
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages:
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "10.0.0"

targets:
  Dickerator:
    type: application
    platform: iOS
    sources:
      - path: Dickerator
        excludes:
          - "**/*.xcassets"
      - path: Dickerator/Resources/Assets.xcassets
    resources:
      - path: Dickerator/Resources
        excludes:
          - "**/*.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dickerator.app
        INFOPLIST_FILE: Dickerator/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseFirestore
      - package: FirebaseSDK
        product: FirebaseStorage
    preBuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        script: |
          # Placeholder for any pre-build scripts
        showEnvVars: false

schemes:
  Dickerator:
    build:
      targets:
        Dickerator: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
